version: "3"
networks:
  gitea:
    external: false
services:
  gitea:
    image: gitea/gitea:1.18.5
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__i18n__LANGS=zh-CN
      - GITEA__i18n__NAMES=简体中文
      - GITEA__time__FORMAT=RFC1123
      - GITEA__time__DEFAULT_UI_LOCATION=Asia/Shanghai
      - GITEA__ui__DEFAULT_THEME=gitea
      - GITEA__other__ENABLE_SITEMAP=true
      - GITEA__other__ENABLE_FEED=true
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
